name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pre-build:
    name: Update version name
    runs-on: ubuntu-latest
    outputs:
      version: "v6.0.4" 
    steps:
      - uses: actions/checkout@v2
#       - uses: actions-rs/toolchain@v1
#         with:
#           toolchain: stable
#           profile: minimal
#           override: true

      - name: Push tag
        env:
          VERSION: "v6.0.4" 
        run: |-
          # set tag and publish current version
          git tag -a "v6.0.4" -m "New tag" 
          git push && git push --tags
          # create master and push
          git switch -c master
          git fetch origin master --depth=1
          git -vvv push -u origin master
      - name: Update To Next Version

